version: '3.8'

services:
  mkdocs:
    image: papillondoc
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    ports:
      - "8000:8000"
